---
#------------------------------------------------------------------------------------------------------
#                       Purpose:
#------------------------------------------------------------------------------------------------------
# This file integrates Kubernetes Secrets with External Secrets to fetch data from AWS Secrets Manager.
# It ensures secure handling of sensitive credentials without embedding them directly in manifests.
#------------------------------------------------------------------------------------------------------
#           Checklist for developers using this ExternalSecret file
#------------------------------------------------------------------------------------------------------
# 1. Replace 'template' in the 'metadata.name' field with the name of your service.
# 2. Update 'secretStoreRef.name' to match your external secrets store.
# 3. Ensure 'data' entries match the keys in the corresponding AWS Secrets Manager entry.
# 4. Verify the 'property' fields in 'data' correctly reference the secret keys in AWS.
#------------------------------------------------------------------------------------------------------

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: template
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    nameternal-secrets: ex
  target:
    # The name of the K8 secret to put the secret in secret.yaml
    name: template
    creationPolicy: Merge
  data:
    # local field (in the secret stringData)
    - secretKey: AUTH0_CLIENT_SECRET
      remoteRef:
        # AWS Secrets Manager secret name
        key: template-dev
        # AWS Secrets Manager secret key
        property: AUTH0_CLIENT_SECRET
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: template-dev
        property: GITHUB_TOKEN
